version: '3'

services:
  # api:
  #   build: .
  #   container_name: dev-recipes-restful
  #   env_file: .env
  #   depends_on: 
  #     - db
  #   restart: always
  #   ports: 
  #     - 9000:80

  mysql:
    image: mysql:latest
    container_name: dev-mysql
    restart: always
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "3306:3306"
    volumes:
      - ./.storage/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "root"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "dev-phpmyadmin"
    depends_on: 
      - mysql
    restart: always
    ports:
      - 9090:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
